# For more info: https://support.atlassian.com/bitbucket-cloud/docs/pipeline-start-conditions/#Pull-Requests

image: node:18

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install code-review-gpt
          script:
            - npm install code-review-gpt
      - step:
          name: Run code review script
          script:
            - npx code-review-gpt review --ci=bitbucket --model=gpt-3.5-turbo
            # - pipe:
            #   variables:
            #     OPENAI_API_KEY: $OPENAI_API_KEY
            #     BITBUCKET_ACCESS_TOKEN: $BITBUCKET_ACCESS_TOKEN
            #     BASE_SHA: $BASE_SHA
